### ISSUE TITLE
Tweet favorite failed. Error was

### ISSUE THREAD

**Issue by ghost** [neojato/T-Hawk#10]
Tweet favorite failed. Error was:
{"name":"Exception"}

options were:
{"method":"POST","payload":"id=1269419297157365761","headers":{"Authorization":"OAuth oauth_consumer_key=\"XXXXXX\", oauth_nonce=\"XXXXXXX\", oauth_signature=\"XXXXXX%XXXXX%3D\", oauth_signature_method=\"XXXX-XXXXX\", oauth_timestamp=\"XXXXX\", oauth_token=\"XXXXX-XXXXX\", oauth_version=\"1.0\""},"escaping":false}

I get this error when trying to retweet or like anything

**Comment by cfoxalot** [comment]
Try this fix here https://github.com/neojato/T-Hawk/pull/13/files

**Comment by neojato** [comment]
See #12 for the latest on issues with the Twitter library used.
