### ISSUE TITLE
Bot retweets from accounts it has blocked

### ISSUE THREAD

**Issue by bobdaduck** [neojato/T-Hawk#11]
Our community wants to keep track of our hashtag, but it isn't uncommon for trolls to spam the hashtag with porn, insults, etc.  The retweet bot retweets all these things /even if they come from accounts the bot has blocked/.  This then makes curation impossible, because the blocked tweets do not show up on the bots profile retweets when signed in as the bot.

**Comment by stritti** [comment]
I think you have to exclude these accounts from search phrase. The blocked accounts are still in the search so the bot find their tweets too.

I removed Retweets for example too: https://github.com/stritti/bot_sarcoidosis/blob/e60962349cd7d01ef44183dfd6977124ccf59f14/Code.gs#L7
