### ISSUE TITLE
Delete / remove retweets?

### ISSUE THREAD

**Issue by epictetito** [neojato/T-Hawk#14]
Hi

This code is proving very useful to me, thanks for sharing it

But there is something that I cannot find to complete it ...

Does anyone know if you can complete this script or perform another one in javascript to be able to delete / remove retweets?

As much as I search, I can't find answers anywhere.

Thanks

**Comment by neojato** [comment]
Apologies on the delayed response here, for additional functions/endpoints beyond what I'm using in this project you should check out the Twitter for GAS library: https://github.com/airhadoken/twitter-lib
