### ISSUE TITLE
Process More then 1 tweet

### ISSUE THREAD

**Issue by wschlotter** [neojato/T-Hawk#4]
Is there a way to process more than one tweet at a time. I found the line to change the number (line 40) but when I change it to anything greater then 1 it errors out the script. I am not looking to spam just want to process a view more during runtime.

**Comment by neojato** [comment]
Hi @wschlotter, this follows the Twitter Search API and can handle upwards of 100. As seen here: https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets

By default, this script returns up to 5 tweets every 10 mins. Potentially there's another error and/or you will need to increase the runtime between triggers.
