### ISSUE TITLE
Empty results seems to clobber since_id

### ISSUE THREAD

**Issue by brubsby** [neojato/T-Hawk#6]
I changed these lines to fix the problem for me, can also submit a PR

```if (tweets) {```
to
```if (tweets.length > 0) {```

the twitter api must send back an object that is truthy but has length 0.

after the since_id was clobbered it made it to where it would then try to retweet already retweeted posts and then die or something

**Comment by neojato** [comment]
Thanks @brubsby!  Checks out for me.
