### ISSUE TITLE
can't get results in twitter 

### ISSUE THREAD

**Issue by skiingmadman** [neojato/T-Hawk#8]
I followed instructions and it seems to run fine with no errors, but I am not seeing any likes or retweets in my twitter account...any thoughts?  setup app in twitter.dev and added resource library, etc..  appreciate  any guidance and support.... no logs to review unfortunately.

**Comment by ChristopherSchek** [comment]
experiencing the same as of today. Attempted to drop the library version to 23. Still not seeing results.

**Comment by skiingmadman** [comment]
I got it to work and then exceeded rate limit by copy and pasting it about 30 times..making it 40 pages of js code. rate limit exceeded..too many actions...only 100/hour.....failed likes count, so ez to hit the limit. I find that RECENT doesn't give me all the latest results....not sure if what is going on there but it kind of works...
[bot1.txt](https://github.com/neojato/T-Hawk/files/4598874/bot1.txt)
